<?xml version="1.0"?>
<package format="2">
  <name>ig_handle</name>
  <version>1.0.1</version>
  <description>ig-handle: a handheld inspector gadget</description>
  
  <author email="aaronjs@g.ucla.edu">Aaron John Sabu</author>
  <author email="adthoms@ucla.edu">Alexander Thoms</author>
  <author email="gearle@uwaterloo.ca">Gabriel Earle</author>
  <maintainer email="aaronjs@g.ucla.edu">Aaron John Sabu</maintainer>
  <maintainer email="adthoms@ucla.edu">Alex Thoms</maintainer>
  <maintainer email="gearle@uwaterloo.ca">Gabe Earle</maintainer>

  <license>MIT</license>
  <url type="repository">https://github.com/aaronjs99/ig_handle</url>
  <url type="bugtracker">https://github.com/aaronjs99/ig_handle/issues</url>
  
  <buildtool_depend>catkin</buildtool_depend>
  
  <build_depend>message_generation</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_export_depend>message_runtime</build_export_depend>
  <build_export_depend>std_msgs</build_export_depend>

  <exec_depend>dt100_driver</exec_depend>
  <exec_depend>flir_boson_usb</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>message_runtime</exec_depend>
  <exec_depend>image_proc</exec_depend>
  <exec_depend>nodelet</exec_depend>
  <exec_depend>rosserial_python</exec_depend>
  <exec_depend>python3-rospkg</exec_depend>
  <exec_depend>rospy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>spinnaker_camera_driver</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>velodyne_driver</exec_depend>
  <exec_depend>velodyne_pointcloud</exec_depend>
  <exec_depend>xsens_mti_driver</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
</package>
