topics:
  heron_sense_raw: /sense
  heron_sense: /sense_heron
  ighandle_sense: /sense_ighandle
  ighandle_sense_details: /sense_ighandle/details
  mocap_pose: /mocap/heron/pose
  mocap_aligned_pose: /mocap/heron/pose/aligned
  mocap_relative_pose: /mocap/heron/pose/relative
  mocap_initialize: /mocap/initialize
  mocap_markers: /mocap/heron/markers
  mocap_potential_objects: /mocap/potential_objects
  mocap_status: /mocap/datacollect_status
  telescope_command_length: /actuators/telescope/command/length
  telescope_state_length: /actuators/telescope/state/length
  telescope_state_status: /actuators/telescope/state/status
  telescope_state_motor_current: /actuators/telescope/state/motor_current
  teensy_pps_time: /sensors/pps/time
  teensy_camera_time: /sensors/camera/time
  teensy_imu_time: /sensors/imu/time
  teensy_timing_status: /sensors/timing/status
  sonar_raw: /sensors/sonar/raw
  sonar_ping360_raw: /sensors/sonar/ping360/raw
  sonar_scan: /sensors/sonar/scan
  sonar_profile: /sensors/sonar/imaging/profile
  sonar_image: /sensors/sonar/imaging/image
  sonar_ping360_diagnostics: /sensors/sonar/ping360/diagnostics
